### ISSUE TITLE
Should we require `hoa/devtools`

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Test#35]
Dear coders,

While rebooting the contributor guide, I realized it would be great that `hoa/test` requires `hoa/devtools`. If one installs Hoa with `composer install --no-dev`, she is going to have no test tools and no devtools, which is what we expect. But when we would like to test, very often, we also would like to check CS, so `hoa/devtools` is required.

Thoughts?

/cc @hoaproject/hoackers

**Comment by osaris** [comment]
Make sense to me.

**Comment by Hywan** [comment]
Ok, here we go.
