### ISSUE TITLE
Documentation clarification needed

### ISSUE THREAD

**Issue by osaris** [hoaproject/Test#45]
Hello,

I'm translating the doc in french and I need clarification on this part because check and verify have the same meaning so the sentence is ambiguous for me : 

https://github.com/hoaproject/Test/blob/386896d351d283b7f193e553f8b82509e5962034/Documentation/En/Index.xyl#L37-L38

Thx

**Comment by Hywan** [comment]
@osaris What about « n'asserte pas que le SUT est vérifié »?
