### ISSUE TITLE
Add a default behaviour to `test:run` to run current test suite

### ISSUE THREAD

**Issue by shulard** [hoaproject/Test#54]
Hello,

I think it can be useful to run the test on the current library by default when running `test:run` command. This is a kind of shortcut for: `test:run -l CurrentLib`

I'm always missing to last parameter because I just want to run current test suite...

Though about that update ?

**Comment by Hywan** [comment]
I guess it's better to have `-d Test` by default instead of `-l currentLibrary`. I reckon `-d .` could work too.

**Comment by Hywan** [comment]
Fixed by #55.
