### ISSUE TITLE
Cannot run tests on Windows using Git Bash

### ISSUE THREAD

**Issue by LukBukkit** [hoaproject/Test#83]
Hello,
I wanted to run the tests for the [Socket Libary](https://github.com/hoaproject/Socket) on Windows, but when I execute the command, I get only a single line of output:
```
$ vendor/bin/hoa test:run
> atoum path: D:\lukas\Coding\PhpstormProjects\Hoaproject\Acl\vendor\atoum\atoum\D:\lukas\Coding\PhpstormProjects\Hoaproject\Acl\vendor\bin\/../atoum/atoum/bin/atoum
```
After this, the programms just waits for termination. I tested it on Ubuntu too and there it works.

My PHP version by the way:
```
$ php --version
PHP 7.0.8 (cli) (built: Jun 21 2016 15:27:20) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```
Thank you for your help!

**Comment by Hywan** [comment]
Hello @LukBukkit,

Please, can you test #84 and tell me if it fixes your issue? Thanks!

**Comment by Hywan** [comment]
The patch in atoum/atoum#688 will only fix the “atoum path” line in the report. The path is incorrectly displayed, but it is correctly used.

**Comment by LukBukkit** [comment]
I've applied #84 and atoum/atoum#688, but it doesn't seem to help.

**Comment by Hywan** [comment]
What is the output please?

**Comment by LukBukkit** [comment]
Again a single line of output:
```
$ vendor/bin/hoa test:run
> atoum path: D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\atoum\atoum\bin\atoum
```
I will try it also on another windows machine.

**Comment by Hywan** [comment]
Can you `var_dump($command)` here https://github.com/hoaproject/Test/blob/master/Bin/Run.php#L334, and give me the result please?

**Comment by LukBukkit** [comment]
Sure
```
$ vendor/bin/hoa test:run
string(329) "D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\bin\atoum --autoloader-file D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\hoa\test\.autoloader.atoum.php --configurations D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\hoa\test\.atoum.php --force-terminal --max-children-number 2 --directories Test"
> atoum path: D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\atoum\atoum\bin\atoum
```

**Comment by Hywan** [comment]
@LukBukkit What happen when execute this command manually, directly on the command-line?

**Comment by LukBukkit** [comment]
Because asciinema don't work on Windows, I recoreded a video: https://www.youtube.com/watch?v=cdhUSuJJSA4

**Comment by LukBukkit** [comment]
Okay when I try to run the command using the Windows command-line it works. If I change the paths a litte bit the command looks like this 
```
vendor/bin/atoum --autoloader-file vendor/hoa/test/.autoloader.atoum.php --configurations vendor/hoa/test/.atoum.php --force-terminal --max-children-number 2 --directories Test/
```
and works in the Git Bash too. 
When I run `test:run` using the Windows cmd, I have the same problem as before:
```
D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket>vendor\bin\hoa.bat test:run
string(329) "D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\bin\atoum --autoloader-file D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\hoa\test\.autoloader.atoum.php --configurations D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\hoa\test\.atoum.php --force-terminal --max-children-number 2 --directories Test"
[38;5;0m> [0m[38;5;0matoum path[0m: D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\atoum\atoum\bin\atoum
^CBatchvorgang abbrechen (J/N)? J
```
Again thanks you for your help to this point. Now I've got a workaround. 😃

**Comment by Hywan** [comment]
But it seems we have an issue on Windows with `Hoa\Console\Processus` then… OK :-].

Can you test those two examples and tell me which one works or not.

Example 1:

```php
$processus = new Hoa\Console\Processus('ls');
$processus->open();
echo $processus->readAll();
```

Example 2:

```php
$processus = new Hoa\Console\Processus('ls');
$processus->on('output', function (Hoa\Event\Bucket $bucket) {
    $data = $bucket->getData();
    echo '> ', $data['line'], "\n";
});
$processus->run();
```

Thanks!

**Comment by LukBukkit** [comment]
**Test Nr.1:**
```
CHANGELOG.md
Client.php
Connection
Exception
Node.php
Processus.php
README.md
Server.php
Socket.php
Test
Transport.php
composer.json
composer.lock
test.sh
vendor
```

**Test Nr.2:**
```
PHP Warning:  Invalid argument supplied for foreach() in D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\hoa\console\Processus.php on line 460

Warning: Invalid argument supplied for foreach() in D:\lukas\Coding\PhpstormProjects\Hoaproject\Socket\vendor\hoa\console\Processus.php on line 460
```

**Comment by Hywan** [comment]
@LukBukkit This is an issue related to `Hoa\Console`. Please, go to https://github.com/hoaproject/Console/issues/79 for the sequel.
